

import { ClientOnly } from './components/ClientOnly'
import { RegisterModel } from './components/models/RegisterModel'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToasterProvider } from './providers/ToasterProvider'
import { LoginModel } from './components/models/LoginModel'
import getCurrentUser from './actions/getCurrentUser'
import { ThemeProvider } from './context/ThemeContext'
import { RentModel } from './components/models/RentModel'
import LoadingModel from './components/models/LoadingModel'
import SearchModel from './components/models/SearchModel'
// import { Suspense } from 'react'
// import Loading from './Loading'





const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const currentUser =  await getCurrentUser()
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider >
        <ClientOnly>
          <ToasterProvider />
          <LoadingModel />
          <SearchModel />
          <RentModel />
          <LoginModel />
          <RegisterModel />
          <Navbar currentUser={currentUser}/>
        </ClientOnly>
        <div className='pb-20 pt-28'>
          {children}
        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}


